#!/bin/bash -eu

ORG_PATH="github.com/rednut"
REPO_PATH="${ORG_PATH}/nsq-cli"

if [ ! -h gopath/src/${REPO_PATH} ]; then
    mkdir -p gopath/src/${ORG_PATH}
    ln -sv ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

pushd $GOPATH

eval $(go env)
go get github.com/rednut/nsq-cli/producer
go get github.com/rednut/nsq-cli/consumer
popd

ls -l $PWD/bin/

